-- =============================================================
-- CE FICHIER EST OBSOLÈTE
-- Les données de test sont désormais dans :
--   17_02_2026_05_donnees_besoins_villes.sql
-- =============================================================
